repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: [--config, .flake8]
        exclude: movies
        language: python
        types: [python]