version: '3.9'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ../env_files/.env.db
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $$POSTGRES_DB -h $$DB_HOST -p $$DB_PORT -U $$POSTGRES_USER"
        ]
      interval: 3s
      timeout: 5s
      retries: 15

  movies:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env.db
      - ./env_files/movies.env
    environment:
      - MAKE_MIGRATIONS=true
      - NEED_TO_CREATE_SUPERUSER=true
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint:
      - /app/entrypoint.sh
